name: Run Test

on:
  workflow_call:
    # environment value here HAS to be defined in caller file using 'with:'
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run tests against
        type: environment
        required: true
        default: STAGING

# Try to make this default to STAGING environment if not defined from caller
jobs:
  echo-environment:
    name:  Echo out env info from call on ${{ inputs.environment }}
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Echo environment for ${{ inputs.environment }}
        env:
          VAR1: ${{ vars.TEST_VARIABLE_1 }}
          FOO1: ${{ secrets.SECRET_TEST_1 }}
        run: |
          echo "${{ inputs.environment }}"
          echo "Secret: ${{ secrets.SECRET_TEST_1 }}"
          echo "Secret as env: ${{ env.FOO1 }}"
          echo "Var: ${{ vars.TEST_VARIABLE_1 }}"
          echo "Var as env: ${{ env.VAR1 }}"
